### ISSUE TITLE
latest versions of Matlab and Vivado Lab Edition

### ISSUE THREAD

**Issue by jpnielsen** [analogdevicesinc/MathWorks_tools#59]
Will the tools work with the latest versions of Matlab and Vivado Lab Edition ?

Mathworks Matlab R2019a Update 3
Vivado 2019.1: Lab Edition - Windows

**Comment by tfcollins** [comment]
R2019a update 3 yes. Vivado 2019.1 no. HDL Coder does not support this Vivado release yet and neither does our HDL branches.

**Comment by tfcollins** [comment]
Closing for now.
