### ISSUE TITLE
Some fixes not merged into 2016a branch

### ISSUE THREAD

**Issue by noonien-d** [analogdevicesinc/MathWorks_tools#9]
It seems that at least all patches up to ac80053adf70792aef5ca2d05d63641ac22a9e1e should be merged to the 2016a branch.

The 2016a branch has issues as described here: https://ez.analog.com/thread/89029-model-based-design-using-simulink-zedboard-and-fmcomms2

**Comment by tfcollins** [comment]
Closing since we do not backport changes and 2016a is out of our support window now.
